CREATE TABLE customer(
                         id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         first_name varchar(255) NOT NULL,
                         last_name varchar(255) NOT NULL,
                         email varchar(255) UNIQUE,
                         address varchar(255) NOT NULL,
                         date_of_birth date,
                         created_at timestamp,
                         customer_type varchar;
);
create table items(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    customer_id int REFERENCES customer(id) ON DELETE SET NULL
)